server:
  port: 18100
  use-forward-headers: true
  servlet:
    context-path: /memberservice

spring:
  datasource:
    initialSize: 10
    maxTotal: 100
    maxIdle: 20
    minEvictableIdleTimeMillis: 60000
    maxWaitMillis: 30000
    testOnBorrow: true
    validationQuery: select now()
    removeAbandonedOnBorrow: true
    removeAbandonedTimeout: 60
    logAbandoned: true
    url: jdbc:h2:mem:dummydb #jdbc:h2:file:~\h2DB\Database;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
    platform: mysql

  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: none
security:
  oauth2:
    client:
      clientId: client
      tokenName: access_token
      userAuthorizationUri: http://35.233.44.8/authentication/oauth/authorize
      accessTokenUri: http://35.233.44.8/authentication/oauth/token
      clientSecret: secret
      scope: read
    resource:
      tokenInfoUri: http://35.233.44.8/authentication/oauth/check_token
      preferTokenInfo: true
      jwt:
        key-uri: http://35.233.44.8/authentication/oauth/token_key
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApAiHmqMydGV3GosgorAB
          dX8jlzOVe+xKWQrhQKBkzQRqoMYtUzJkAbeHm4IbG8E3P22NHHW4XW9e5ReDSkqx
          o1n7g9rI0VGNiUPwIikf6+IhznjctjUaT+wKpU9OCMtAglq78gLhZcRCxXqLpkLE
          d9NFQPhcqFnKEzdIa8s+zgN/SfsQTmc7AAB5Jq75gjFG4WRc0ijGj7NfeClqWmjL
          W9J2EcsrmWHfFAlqAzB9Cz/no1ZmF5zBKKXEMlcUn7iM5eQ+qBshnrqUtO44ziX2
          wEXJKhlLy4W8VwvrnF596w3S94A2TTI+gF4xEg5GjI4hsUQHUmkf0tAeQyYnesNr
          TwIDAQAB
          -----END PUBLIC KEY-----
logging:
   level:
     com:
       sanluna: DEBUG
     org:
       springframework: DEBUG

spring.main.allow-bean-definition-overriding: true

security.oauth2.tenantclient.access-token-uri: http://localhost:18000/authentication/oauth/token
security.oauth2.tenantclient.tenantclient-id: client
security.oauth2.tenantclient.tenantclient-secret: secret
gwr.multitenancy: true