server:
  port: 18100
  use-forward-headers: true
  servlet:
    context-path: /memberservice

spring:
  datasource:
    initialSize: 10
    maxTotal: 100
    maxIdle: 20
    minEvictableIdleTimeMillis: 60000
    maxWaitMillis: 30000
    testOnBorrow: true
    validationQuery: select now()
    removeAbandonedOnBorrow: true
    removeAbandonedTimeout: 60
    logAbandoned: true
    url: jdbc:h2:mem:dummydb #jdbc:h2:file:~\h2DB\Database;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop