apiVersion: v1
kind: Namespace
metadata:
  name: gwr-api
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gwr-member-service
  labels:
    app: gwr-member-service
  namespace: gwr-api
  annotations:
    moniker.spinnaker.io/stack: member
    moniker.spinnaker.io/detail: service
spec:
  selector:
    matchLabels:
      app: gwr-member-service
  replicas: 1
  template:
    metadata:
      labels:
        app: gwr-member-service
    spec:
      containers:
      - name: master
        image: eu.gcr.io/sanluna-gwr/gwr-member-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 18100
        readinessProbe:
          httpGet:
            path: /memberservice/status/health
            port: 18100
            httpHeaders:
            - name: Content-Type
              value: application/json
            - name: Accept
              value: application/json
          periodSeconds: 8
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 6
          initialDelaySeconds: 20
        livenessProbe:
          httpGet:
            path: /memberservice/status/health
            port: 18100
            httpHeaders:
            - name: Content-Type
              value: application/json
            - name: Accept
              value: application/json
          periodSeconds: 4
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 6
          initialDelaySeconds: 20
        env:
        - name: JAVA_OPTS
          value: -Xms128m -Xmx128m
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 150m
            memory: 256Mi
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gwr-member-service
  namespace: gwr-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gwr-member-service
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
---
kind: Service
apiVersion: v1
metadata:
  name: gwr-member-service
  labels:
    app: gwr-member-service
    service: gwr-member-service
  namespace: gwr-api
  annotations:
    moniker.spinnaker.io/stack: member
    moniker.spinnaker.io/detail: service
spec:
  type: NodePort
  selector:
    app: gwr-member-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 18100